stellarwp/telemetry

src/ActivationHook.php, src/ActivationRedirect.php, src/Contracts/DataProvider.php, src/Contracts/Redirection.php, src/Contracts/Request.php, src/Contracts/Runnable.php, src/Contracts/Template.php, src/DebugDataProvider.php, src/ExampleStarter.php, src/OptInTemplate.php, src/RegisterSiteRequest.php, src/Starter.php, src/TelemetrySendDataRequest.php, src/Template.php, tests/wpunit/RegisterSiteTest.php, tests/wpunit/TelemetrySendDataTest.php
Reason I'm adding this as part of the telemetry library, is that the Opt In is part of our responsibility so we need to be able to handle a way to automatically redirect to a known area where we'll inject the template's code, but that will be handled in the plugin.
This is also my first effort to remove the God-class Starter, and to move individual parts of the library to their own usable classes.
=> Added redirection on plugin activation.

src/OptInTemplate.php, src/views/optin.php
Modal now closes when clicking on Skip, and sends a GET param when agreeing so the implementing plugin can act.
This PR also removes the HTML code from the OptinTemplate class and moves it to its own views/optin.php template file, using $args passed from the load_template function.
=> Opt-In Modal Improvements

src/Telemetry/Cron_Subscriber.php, src/Telemetry/Opt_In_Subscriber.php, src/views/optin.php
This fixes a bug where the site data would be sent to the Telemetry server as soon as it loaded without the user being opted in. Instead, we register the site as soon as the user agrees with the opt-in modal.
=> Require Opt-In Before Site Registration

README.md, src/Telemetry/Config.php, src/Telemetry/Telemetry.php
This adds a new config option for defining the Telemetry Server URL so plugins aren't locked in to any single server instance. It also removes places where we were statically defining a URL.
=> Add Server URL Config

src/Telemetry/Last_Send.php
The `DateTimeInterface::diff()->s` property only goes up to 60 before adding one to the minute property and resetting back to 0.  This update adds the seconds to the last ran date creating a next run date, and compares the value to now.
=> Bugfix: Updates is_expired to use a more reliable date diff

src/Telemetry/Telemetry.php
The telemetry server was throwing a method exception when the user data was POSTed to the server. This json_encodes the data and sends it how the server expects it.
=> Update Opt-In data to send what server expects

src/Telemetry/Uninstall.php
After restructuring directories, this reference was missed which causes the uninstall method to fail and keep the plugin from uninstalling itself.
=> Fix Uninstall Method Fatal Error

src/Telemetry/Telemetry/Telemetry_Subscriber.php
We noticed that sometimes the ajax request during the 'shutdown' action would fail and prevented the Telemetry data from being sent to the Telemetry server. After digging in some, we realized that it was failing due to an invalid cert and from [the WordPress codex](https://developer.wordpress.org/reference/classes/WP_Http/request/#parameters), I found that you can include `'sslverify' => false` to prevent the request from trying to validate the certificate.
Before adding that parameter, the request failed unexpectedly on my local machine that I was able to replicate the error we were seeing on a Nexcess server. Adding the parameter allowed the request to continue and telemetry data was successfully sent to the server.
This should resolve occasional issues on environments where an invalid …
=> Prevent request from trying to verify ssl cert

src/Telemetry/Last_Send/Last_Send.php
Sometimes when the timestamp is retrieved, it's the cached value and not the actual value in the database. By making this method public, it can be used elsewhere.
=> Make method public to avoid get_option cache

src/Telemetry/Config.php, src/Telemetry/Core.php, src/Telemetry/Exit_Interview/Exit_Interview_Subscriber.php, src/Telemetry/Exit_Interview/Template.php, src/Telemetry/Opt_In/Opt_In_Subscriber.php, src/Telemetry/Opt_In/Opt_In_Template.php, src/Telemetry/Telemetry/Telemetry.php, src/Telemetry/Uninstall.php, tests/wpunit/ConfigTest.php
Adds `Config::set_stellar_slug( $unique_plugin_slug )`
Adds `Config::get_stellar_slug() : string`
Updates telemetry send to check the is_active status from the status class.
Adds slugs to the telemetry send.
=> Adds Config::stellar_slug

README.md, src/Telemetry/Exit_Interview/Template.php, src/Telemetry/Opt_In/Opt_In_Subscriber.php, src/Telemetry/Opt_In/Opt_In_Template.php
Since plugins will want to customize opt-in and exit-interview modals independently, it makes more sense to use the `stellar_slug` instead of `hook_prefix`.
=> Use Stellar Slug for Template Configuring Hooks

src/Telemetry/Last_Send/Last_Send_Subscriber.php, src/Telemetry/Opt_In/Opt_In_Subscriber.php
The options need to be set any time the plugin is active because the plugin tries to send telemetry data on shutdown. Therefore the options need to exist before that method is called. Also, the plugin could be activated outside of the `admin_init`—using WP CLI or a MU plugin that automatically activates plugins.
Closes #51
=> Initialize options on init instead of admin_init

src/Telemetry/Telemetry/Telemetry.php
This adds the opted-in plugin slugs so the telemetry data can be linked with the correct brands on the server.
=> Add stellar_slugs to the register site request

README.md, composer.json
The strauss_overload messes with the namespace overrides that Strauss is meant to perform. Instead, to force Strauss to copy/address directories, you can set up fake namespaces for PSR-4 autoloading and that causes Strauss to properly copy the files. In this library's case, it copies `src/Telemetry`, `src/views`, and `src/resources`.
=> Avoid recommending strauss_overload

src/resources/js/scripts.js
The deactivate button needs re-activating if the form contains errors.
=> [FRAME-125] Exit Interviews Deactivate Button Disabling All Options

src/views/optin.php
Although nobody should be loading the library on a WP Admin page that doesn't include the `$_GET['page']` variable, we should still check to make sure that it exists before using it. 
This change will allow developers to add the telemetry action to load the modal on any page in the WordPress admin as long as it is only called once. 
for example this now works:
```
add_action( 'admin_footer', function(){
do_action( 'stellarwp/telemetry/telemetry-starter/optin' );
}, 1, 0 );
```
=> Bug: Check variable before using it.

README.md, src/Telemetry/Admin/Resources.php, src/Telemetry/Exit_Interview/Template.php, src/Telemetry/Last_Send/Last_Send.php, src/Telemetry/Opt_In/Opt_In_Template.php, src/Telemetry/Opt_In/Status.php, src/Telemetry/Telemetry/Telemetry.php
...after uses of `Config::get_hook_prefix()` and `Config::get_stellar_slug()`
All of these that are in the readme are listed with the slash, the rest aren't in the readme.
All have been properly deprecated. 
I know the variable didn't need to be set first in some cases, but it makes it a bit clearer what is going on - something that can be difficult with deprecated filters.
TBDs for version number need to be changed.
Also fixed a typo that was bugging me 😉
=> Deprecate and replace several filter slugs that are missing slashes

README.md, src/Telemetry/Admin/Admin_Subscriber.php, src/Telemetry/Config.php, src/Telemetry/Contracts/Template_Interface.php, src/Telemetry/Core.php, src/Telemetry/Exit_Interview/Exit_Interview_Subscriber.php, src/Telemetry/Exit_Interview/Template.php, src/Telemetry/Opt_In/Opt_In_Subscriber.php, src/Telemetry/Opt_In/Opt_In_Template.php, src/Telemetry/Opt_In/Status.php, src/Telemetry/Telemetry/Telemetry.php, src/Telemetry/Uninstall.php, src/views/optin.php
This is a major upgrade that lets plugins define multiple `stellar_slugs`. The use case came from TEC where they load the library from a shared library for several of their plugins. Registering multiple stellar_slugs will allow TEC to manually add opt-in modals for each add-on using the shared library.
Here's a walkthrough screencast of the changes: http://p.tri.be/v/oQXjX4
=> [FRAME-138]: Allow Multiple Stellar Slugs

src/Telemetry/Opt_In/Status.php
...so order of plugins in the $option['plugins'] array doesn't matter.
=> Correct the logic in Status->get()

src/Telemetry/Uninstall.php
If the parent plugin is installed, but not activated, `stellarwp_telemetry` is not set. When deleting the plugin, the default value of `false` is passed to the `count()` function which will throw a warning on php 7.2+ and fatal error on 8.0+.
**Steps to recreate**
- Install Kadence Blocks (3.1.*) on a site without a `stellarwp_telemetry` entry in options table
- Do not activate plugin
- Attempt to delete plugin via wp-admin
=> Prevent fatal error if parent plugin is deleted without activating

src/Telemetry/Opt_In/Status.php, src/Telemetry/Telemetry/Telemetry.php
This will help provide a point of reference if the user opt-in needs to be sent again or we need it for some other purpose down the road.
For reference, the value stored in the database is the same json-encoded payload sent to the server during user opt-in:
```JSON
{
"name":"admin",
"email":"admin@telemetry-library.lndo.site",
"plugin_slug":"telemetry-library"
}
```
=> Store the opt-in user details in the options

dev/public/wp-content/plugins/library-testing/library-testing.php, src/Telemetry/Events/Event.php, src/Telemetry/Events/Event_Subscriber.php
This adds functionality to cache all events for the request until the `shutdown` action. Then during `shutdown` each event request is sent in a similar fashion to how we send the telemetry data.
1. A request is sent to the ajax endpoint
2. A new request is created during the ajax request to actually send the event to the server
This should keep the user from needing to wait for the requests to send, but it does not prevent the server from being overloaded if a plugin sends a large number of requests on each page load.
=> [FRAME-176]: Delay Events Until Shutdown

src/Telemetry/Opt_In/Opt_In_Subscriber.php, src/Telemetry/Opt_In/Opt_In_Template.php, src/Telemetry/Telemetry/Telemetry.php, src/views/optin.php, tests/wpunit/TemplateTest.php
This adds the `opt_in_text` and properly passes that along in the opt-in request to support https://github.com/stellarwp/telemetry-server/pull/72
=> [FRAME-170]: Add functionality to pass opt_in_text to opt-in

codeception.dist.yml, composer.json, composer.lock, src/Telemetry/Contracts/Template_Interface.php, src/Telemetry/Exit_Interview/Template.php, src/Telemetry/Opt_In/Opt_In_Template.php, tests/wpunit/ConfigTest.php, tests/wpunit/CoreTest.php, tests/wpunit/EventTest.php, tests/wpunit/LastSendTest.php, tests/wpunit/StatusTest.php, tests/wpunit/TelemetrySubscriberTest.php, tests/wpunit/Telemetry_Test.php, tests/wpunit/TemplateTest.php
This handles setting up code coverage measuring and improves our test coverage quite a bit.
You can verify this locally with Slic.
First, you'll need to start XDebug to use it as a driver with:
```sh
slic xdebug on
```
Then you can run the tests and generate the coverage report in the `tests/_output` directory:
```sh
slic run --coverage-html tests/_output
```
=> Improve Test Coverage
